### Ingest a new battery change for a device
POST http://localhost:7071/v2/batterychanges
Content-Type: application/json
Accept: application/json

{
  "DeviceId": "Sensor1"
}

### Get battery changes for the last 24 hours for a specific device
GET http://localhost:7071/v2/batterychanges/last24h/
Accept: application/json

### Get the latest battery change for a specific device
GET http://localhost:7071/v2/batterychanges/latest/
Accept: application/json

