name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'server/src/**'
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: rg-jamobeachweatherstation-test
  AZURE_FUNCTIONAPP_NAME_TEST: func-jamobeachweatherstationapi-test
  AZURE_FUNCTIONAPP_NAME_PROD: func-jamobeachweatherstationapi-prod
  AZURE_BICEP_FILE: server/iac/main.bicep
  AZURE_FUNCTIONAPP_PACKAGE_PATH: server/src/BeachWeatherStation.Worker
  DOTNET_VERSION: 9.0.x

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release -r win-x64 --output ./output
        popd
        
    - name: Upload build
      uses: actions/upload-artifact@v4
      with:
        name: functionapp-package
        path: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'        
    



  deploy-to-test:
    runs-on: windows-latest
    needs: build
    environment: dev
    steps:

    - name: Download build
      uses: actions/download-artifact@v4
      with:
        name: functionapp-package
        path: 'azure-functionapp-package'

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_TEST }}
        package: 'azure-functionapp-package'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_TEST }}

  # deploy-to-production:
  #   runs-on: windows-latest
  #   environment: prod
  #   steps:
  #   - name: 'Checkout GitHub Action'
  #     uses: actions/checkout@v3

  #   - name: 'Resolve Project Dependencies Using Dotnet'
  #     shell: pwsh
  #     run: |
  #       pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
  #       dotnet build --configuration Release -r win-x64 --output ./output
  #       popd

  #   - name: 'Run Azure Functions Action'
  #     uses: Azure/functions-action@v1
  #     id: fa
  #     with:
  #       app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_PROD }}
  #       package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
  #       publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_PROD }}